### ISSUE TITLE
Can you provide the pretrained model?

### ISSUE THREAD

**Issue by wxxxxxxh** [jixiaozhong/RealSR#1]
Hi~
Thanks for your great job in real image super resolution.
I wonder can you provide the pretrained model (Track 2) to help me do some evaluation on my onw dataset?
It's important for me! So, if possible, please release it on Github~
Thank you very much!

**Comment by jixiaozhong** [comment]
Thanks for your watching. [Pre-trainded models](https://github.com/jixiaozhong/RealSR/blob/master/README.md#L76) are available.
