### ISSUE TITLE
Inference results conflict? 

### ISSUE THREAD

**Issue by innat** [jixiaozhong/RealSR#29]
Interesting work. Thanks for sharing. 

However, I have tried to inference on some samples with the provided pretrained weights. But for some reason, I couldn't get the expected results. I tried with both [executable files](https://github.com/jixiaozhong/RealSR#update---may-26-2020) and also [source files](https://github.com/jixiaozhong/RealSR#dependencies-and-installation).  For example, while using source files, I have checked both weights (**DF2K.pth** and **DPED.pth**). Please see below:

## Input
![input](https://user-images.githubusercontent.com/17668390/99572700-41118a80-29ff-11eb-8999-93dbbae2dc8d.png)

## Using DF2K
![DIV2K](https://user-images.githubusercontent.com/17668390/99572772-5d152c00-29ff-11eb-95df-5fc394e0b26c.png)

## Using DPED
![DPED](https://user-images.githubusercontent.com/17668390/99572787-656d6700-29ff-11eb-83b4-ba06fc66bf0d.png)

Now, as it's demonstrated the [visual results](https://github.com/jixiaozhong/RealSR#visual-results) here, I expected the same or reasonable results. Any catch? 

Apart from this, here is another issue, in the testing time, isn't it possible to place multiple low-resolution images at a time? For example, as demonstrated [here](https://github.com/jixiaozhong/RealSR#testing), if I place (let's say) 5 images in `'dataroot_LR' -- test images dir`; it throws `CUDA out of memory: RunTimeError`.

**Comment by usstdqq** [comment]
you got an oom error as the error message suggested... what's your image resolution and GPU memory... you can try to input 5 100x100 resolution images and it should be fine.

**Comment by innat** [comment]
I got errors for trying to inference more than one image. Let's forget that for now. I'm getting the above result from one image, any catch?.

**Comment by usstdqq** [comment]
your LR input image has some blocking artifacts already and is prob different from the distribution of the LR training data. can you try to downsample the image by a factor of 2 or 4 and try again? those blocking artifacts might be surpressed by downsampling.
