### ISSUE TITLE
Comparison with Baidu image_quality_enhance

### ISSUE THREAD

**Issue by jixiaozhong** [jixiaozhong/RealSR#3]
We compare RealSR with [Baidu image_quality_enhance](https://ai.baidu.com/tech/imageprocess/image_quality_enhance).
Here is an image from **their test examples**.
![1](https://user-images.githubusercontent.com/22931606/82902957-d244fe80-9f92-11ea-9fc4-810fc3743896.jpg)

Baidu result:
![rec_lr](https://user-images.githubusercontent.com/22931606/82902991-dec95700-9f92-11ea-8ff8-6db6517f1f38.png)
![crop_lr](https://user-images.githubusercontent.com/22931606/82903040-f274bd80-9f92-11ea-8abf-601f55c3224a.png)

RealSR result:
![rec_hr](https://user-images.githubusercontent.com/22931606/82903340-61eaad00-9f93-11ea-8794-c8ed0688f36b.png)
![crop_hr](https://user-images.githubusercontent.com/22931606/82903347-64e59d80-9f93-11ea-8d44-9212e74b2dd5.png)

**Comment by yldn** [comment]
impressive

**Comment by tyshiwo** [comment]
Amazing!

**Comment by splinter21** [comment]
Niubility！
