### ISSUE TITLE
Using lower resolution image gives better result

### ISSUE THREAD

**Issue by skerit** [jixiaozhong/RealSR#5]
I have some old DV footage I'm testing RealSR on. The source size is 1024x576 pixels.
There are lots of artifacts and noise in it.

I first tried to upscale it to 4096px with RealSR, but there was nearly **no** improvement in the quality. It's almost a carbon copy of the original.

Then I tried something else: I downscaled the original to 512x288 pixels, and upscaled THAT to 2048px. And the result was **amazing**. No more noise, everything looks quite sharp, most halos are even gone, ... (The result in the headlight alone, wow.)

I uploaded the 4 images here, you can compare the 2 inputs to the 2 outputs:
http://www.framecompare.com/image-compare/screenshotcomparison/7776WNNX

Now the question is: why is that? Why did I first have to downscale the image in order to get a better result? It's kind of strange, because some of the details did get lost in the conversion from the 1024px to the 512px image. Could I somehow get an even better result with the original 1024px source?

**Comment by jixiaozhong** [comment]
Thanks for your interesting try.
I compare 4096px vs 2048px in the link.  2048px has less noise, but 4096px are sharper in detail.
Downscaling removes noise/artifacts, so using a lower resolution will give a clean result.
You can also first use RealSR, and then downscale the result. It probably generates a sharp and clean result.

**Comment by skerit** [comment]
Yeah, the 4096px version is a bit sharper, but it isn't that much better than doing a regular resize in the GIMP. Though it did remove *some* of the noise, too.

I'm just still amazed at the 512px to 2048px version. It's so amazing :)

**Comment by splinter21** [comment]
The downsampled 512x288 image is better visualized compared with the original one.....
why?

**Comment by splinter21** [comment]
I downloaded the four images, but the resolutions are the same.
