### ISSUE TITLE
When I enable TTA mode,the program crashed...

### ISSUE THREAD

**Issue by chunxiaoyi** [jixiaozhong/RealSR#6]
System: Windows 10 1909
GPU: 1050TI
Drive: NVIDIA 446.14

When I enable TTA mode,the program crashed...
And the program shows 

E:\Program Files\realsr>realsr-ncnn-vulkan.exe -i [图片地址] -o 123.png -x
[0 GeForce GTX 1050 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce GTX 1050 Ti]  buglssc=0  bugsbn1=0  bugihfa=0
[0 GeForce GTX 1050 Ti]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
decode 708 764 3
vkWaitForFences failed -4
0.00%
vkQueueSubmit failed -4
6.25%
vkQueueSubmit failed -4
12.50%
vkQueueSubmit failed -4
18.75%
vkAllocateMemory failed -2

After the "decode 708 764 3" shows,one of my monitor turns to black(I have 2 monitors,the other is still work) and I have to re-plug HDMI cable to make it rework.

Is the reason that my VRAM is too small?Can I resolve it except upgrade my hardware?

SOLVED: the reason is default tile-size is too big,then I **add -t 32**,it worked.

Another question is when I input a big photo,the program seems work not as good as a small picture ,I must cut the big photo or zoom it out to get the better results.

Thanks a lot,I am not good at English,please forgive me if there are anything wrong in this issue :)

**Comment by nihui** [comment]
fixed in the latest realsr-ncnn-vulkan code
please grab the new binary from
https://github.com/nihui/realsr-ncnn-vulkan/releases
